#!/bin/sh

# Startup the system
/bin/mount -a
/bin/mkdir -p /dev/pts /dev/shm
/bin/mount -t devpts devpts /dev/pts
/bin/mount -t debugfs none /sys/kernel/debug
/bin/mkdir /var/tmp
/bin/mkdir -p /run/lock/subsys
/sbin/swapoff -a
#/bin/hostname -F /etc/hostname

#/sbin/mknod console c 5 1
#/sbin/mknod null    c 1 3

#/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/sbin/mdev -d

/bin/sh /usr/smartsoc/smartsoc_start.sh
